CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON * . * TO 'admin'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS intranet;
GRANT ALL ON intranet.* TO 'admin'@'%';

CREATE DATABASE IF NOT EXISTS nextcloud;
GRANT ALL ON nextcloud.* TO 'admin'@'%';

CREATE DATABASE IF NOT EXISTS glpi;
GRANT ALL ON glpi.* TO 'admin'@'%';